### ISSUE TITLE
Health metrics for device

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#238]
This issue is to open the discussion about health metrics for a device. Currently we see some common issues when devices are deployed, such as connectivity issues or hardware problems to name the most common ones.

We suggest adding a property to the device indicating the device `health`, in which we can collect various metrics, some calculated in the firmware, and some on the platform. Current proposals:

### Platform checks

1. Total number of points stored, versus maximum amount (based on device creation and last update). For this to work, we would need to either assume default interval (1' in sensors except PM), or have a way to retrieve that from the physical device via `hardware_info` for instance
2. Delta between reading time and reception time: this can indicate issues regarding connectivity, but it needs to have the information of the publication interval to make sense. Currently, as we understand, ingestion time is not stored, so probably it's not worth including it
3. Missing sensors (combination between platform and device check) could highlight particular issues with the hardware if a sensor (or all the sensors) disappears.

### Firmware checks

This could be sent on a `/device/<token>/health` mqtt topic, and ingested on the `health` table for later. Could be sent `ad-hoc`, or on boot:
1. Missing sensors, as above
2. Connectivity timeouts
3. SD card issues
4. Too-frequent resets
5. Last reset reason (available via firmware)
6. Reason for WARNING state of the device

@pral2a @vicobarberan please provide inputs to build it progressively.

**Comment by oscgonfer** [comment]
Adding to this topic, a possibility would be to implement simple device metrics, as already suggested here https://github.com/fablabbcn/smartcitizen-api/issues/100#issuecomment-446579722 for those checks that can be done in platform.

A proposal would be:

```
health:
    # on device data ingestion, calculated by the platform
    total_data_points:  # number of data points in total
    data_gaps: #% of data gaps in the whole period based on sample interval (to retrieve from hardware info?)
    missing_sensors: # list
    # filled from a health topic on the mqtt. JSON directly to allow flexibility
    hardware_report: #json sent directly from the hardware
```

The `hardware_report` could be directly ingested from a `/device/token/health` the hardware sends including at least:

- `last_reset_cause`
- `publication_interval` (?)
- `wifi rssi`
