### ISSUE TITLE
Serialize device notifications in grouped json

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#306]
Currently we serialize notifications settings per device as:

```
device:
  notify_stopped_publishing: false
  notify_low_battery: false
```

This is to track a **minor** change to serialize them jointly:

```
device:
  notifications:
    stopped_publishing: false
    low_battery: false
```

Just cleaner. Not much else
